<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="container" nsURI="http://momot.big.tuwien.ac.at/examples/icmt/container/1.0"
    nsPrefix="container">
  <eClassifiers xsi:type="ecore:EClass" name="ContainerModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stack" lowerBound="1" upperBound="-1"
        eType="#//Stack" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextContainer" eType="#//Container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
        upperBound="-1" eType="#//Container" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="travelDistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stack">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topContainer" eType="#//Container"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onTopOf" eType="#//Container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="successor" eType="#//Container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="on" eType="#//Stack"/>
  </eClassifiers>
</ecore:EPackage>
